export const types = {
  MUSICPLAYER_SWITCHON: "MUSICPLAYER_SWITCHON",
  MUSICPLAYER_SETVOLUME: "MUSICPLAYER_SETVOLUME",
  MUSICPLAYER_SETPLAYLIST: "MUSICPLAYER_SETPLAYLIST",
  MUSICPLAYER_SETCURRENTSONGPLAYING: "MUSICPLAYER_SETCURRENTSONGPLAYING",
};
